-- DDL generated by Postico 1.5.12
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE account_balances (
    id BIGSERIAL PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    date timestamp with time zone,
    available_balance_cents bigint,
    current_balance_cents bigint,
    credit_limit_cents bigint
);

CREATE TABLE account_balances (
    id BIGSERIAL PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    date timestamp with time zone,
    available_balance_cents bigint,
    current_balance_cents bigint,
    credit_limit_cents bigint
);

ALTER TABLE account_balances ADD COLUMN account_id bigint REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX account_balances_pkey ON account_balances(id int8_ops);
CREATE INDEX account_balances_account_id_date_desc ON account_balances(account_id int8_ops,date timestamptz_ops DESC);
CREATE INDEX account_balances_user_id_date_desc ON account_balances(user_id int8_ops,date timestamptz_ops DESC);


INSERT INTO table1 VALUES(1,2);
UPDATE foo set f = 1 where id = 2;